### ISSUE TITLE
Doesnt work with python3

### ISSUE THREAD

**Issue by tingvarsson** [tonix64/python-installcab#2]
On Arch python defaults to python3. It is generally it is a good idea to write version independent code when stating only python in the header.
Workaround was to call it with python2 of course, and then it worked as intended.

> Traceback (most recent call last):
>   File "/umaro/git/python-installcab/installcab.py", line 305, in <module>
>     process_files(output_files)
>   File "/umaro/git/python-installcab/installcab.py", line 243, in process_files
>     install_dll(file_path)
>   File "/umaro/git/python-installcab/installcab.py", line 214, in install_dll
>     dest_dir = get_dll_destdir(dll_path)
>   File "/umaro/git/python-installcab/installcab.py", line 65, in get_dll_destdir
>     arch = check_dll_arch(dll_path)
>   File "/umaro/git/python-installcab/installcab.py", line 85, in check_dll_arch
>     if 'x86-64' in out:
> TypeError: a bytes-like object is required, not 'str'

**Comment by strycore** [comment]
I did not have too many issues running the code in python 3. The issue here is that the output of check_output needs a decode() call to cast the value to a string.

Here is the implementation I made, it works under Python 3: https://github.com/lutris/lutris/blob/master/lutris/util/wine/cabinstall.py
